version: '3.8'

services:
  flask-app:
    build: .
    ports:
      - "5003:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - FLASK_APP=app.py
    volumes:
      - .:/app
    restart: unless-stopped
    command: ["python", "app.py"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3